digraph "Code Property Graph" {
	1 [label="1	int curl_mvsnprintf ( char * buffer , size_t maxlength , const char * format , va_list ap_save ) {" shape=box]
	1 -> 4 [color=blue]
	1 -> 6 [color=blue]
	1 -> 7 [color=blue]
	2 [label="2	int retcode ;" shape=box]
	3 [label="3	struct nsprintf info ;" shape=box]
	3 -> 4 [color=blue]
	4 [label="4	info . buffer = buffer ;" shape=box]
	4 -> 9 [color=blue]
	4 -> 10 [color=blue]
	4 -> 5 [color=blue]
	5 [label="5	info . length = 0 ;" shape=box]
	5 -> 9 [color=blue]
	5 -> 6 [color=blue]
	6 [label="6	info . max = maxlength ;" shape=box]
	6 -> 8 [color=blue]
	6 -> 9 [color=blue]
	6 -> 10 [color=blue]
	7 [label="7	retcode = dprintf_formatf ( & info , addbyter , format , ap_save ) ;" shape=box]
	7 -> 8 [color=blue]
	7 -> 12 [color=blue]
	8 [label="8	if ( ( retcode != - 1 ) && info . max ) {" shape=box]
	8 -> 9 [color=red]
	9 [label="9	if ( info . max == info . length ) info . buffer [ - 1 ] = 0 ;" shape=box]
	9 -> 9 [color=red]
	9 -> 10 [color=red]
	10 [label="10	else info . buffer [ 0 ] = 0 ;" shape=box]
	12 [label="12	return retcode ;" shape=box]
}
