digraph "Code Property Graph" {
	1 [label="1	int jbig2_decode_generic_mmr ( Jbig2Ctx * ctx , Jbig2Segment * segment , const Jbig2GenericRegionParams * params , const byte * data , size_t size , Jbig2Image * image ) {" shape=box]
	1 -> 8 [color=blue]
	1 -> 10 [color=blue]
	1 -> 3 [color=blue]
	1 -> 4 [color=blue]
	2 [label="2	Jbig2MmrCtx mmr ;" shape=box]
	3 [label="3	const int rowstride = image -> stride ;" shape=box]
	3 -> 16 [color=blue]
	3 -> 12 [color=blue]
	4 [label="4	byte * dst = image -> data ;" shape=box]
	4 -> 16 [color=blue]
	4 -> 12 [color=blue]
	4 -> 13 [color=blue]
	4 -> 15 [color=blue]
	5 [label="5	byte * ref = NULL ;" shape=box]
	5 -> 13 [color=blue]
	6 [label="6	int y ;" shape=box]
	7 [label="7	int code = 0 ;" shape=box]
	7 -> 18 [color=blue]
	8 [label="8	jbig2_decode_mmr_init ( & mmr , image -> width , image -> height , data , size ) ;" shape=box]
	9 [label="9	for ( y = 0 ;" shape=box]
	9 -> 10 [color=blue]
	9 -> 11 [color=blue]
	10 [label="10	y < image -> height ;" shape=box]
	10 -> 18 [color=red]
	10 -> 12 [color=red]
	10 -> 13 [color=red]
	10 -> 14 [color=red]
	11 [label="11	y ++ ) {" shape=box]
	11 -> 10 [color=blue]
	11 -> 11 [color=blue]
	12 [label="12	memset ( dst , 0 , rowstride ) ;" shape=box]
	13 [label="13	code = jbig2_decode_mmr_line ( & mmr , ref , dst ) ;" shape=box]
	13 -> 18 [color=blue]
	13 -> 14 [color=blue]
	14 [label="14	if ( code < 0 ) return code ;" shape=box]
	14 -> 10 [color=red]
	14 -> 11 [color=red]
	14 -> 14 [color=red]
	14 -> 15 [color=red]
	14 -> 16 [color=red]
	15 [label="15	ref = dst ;" shape=box]
	15 -> 13 [color=blue]
	16 [label="16	dst += rowstride ;" shape=box]
	16 -> 16 [color=blue]
	16 -> 12 [color=blue]
	16 -> 13 [color=blue]
	16 -> 15 [color=blue]
	18 [label="18	return code ;" shape=box]
}
