digraph "Code Property Graph" {
	1 [label="1	int jbig2_decode_halftone_region ( Jbig2Ctx * ctx , Jbig2Segment * segment , Jbig2HalftoneRegionParams * params , const byte * data , const size_t size , Jbig2Image * image , Jbig2ArithCx * GB_stats ) {" shape=box]
	1 -> 32 [color=blue]
	1 -> 34 [color=blue]
	1 -> 35 [color=blue]
	1 -> 38 [color=blue]
	1 -> 41 [color=blue]
	1 -> 11 [color=blue]
	1 -> 12 [color=blue]
	1 -> 13 [color=blue]
	1 -> 45 [color=blue]
	1 -> 15 [color=blue]
	1 -> 47 [color=blue]
	1 -> 17 [color=blue]
	1 -> 49 [color=blue]
	1 -> 23 [color=blue]
	1 -> 25 [color=blue]
	1 -> 29 [color=blue]
	2 [label="2	uint32_t HBPP ;" shape=box]
	3 [label="3	uint32_t HNUMPATS ;" shape=box]
	4 [label="4	uint8_t * * GI ;" shape=box]
	5 [label="5	Jbig2Image * HSKIP = NULL ;" shape=box]
	5 -> 23 [color=blue]
	6 [label="6	Jbig2PatternDict * HPATS ;" shape=box]
	7 [label="7	int i ;" shape=box]
	8 [label="8	uint32_t mg , ng ;" shape=box]
	9 [label="9	int32_t x , y ;" shape=box]
	10 [label="10	uint8_t gray_val ;" shape=box]
	11 [label="11	memset ( image -> data , params -> HDEFPIXEL , image -> stride * image -> height ) ;" shape=box]
	12 [label="12	if ( params -> HENABLESKIP == 1 ) {" shape=box]
	12 -> 13 [color=red]
	13 [label="13	jbig2_error ( ctx , JBIG2_SEVERITY_WARNING , segment -> number , \"unhandled option HENABLESKIP\" ) ;" shape=box]
	15 [label="15	HPATS = jbig2_decode_ht_region_get_hpats ( ctx , segment ) ;" shape=box]
	15 -> 16 [color=blue]
	15 -> 41 [color=blue]
	15 -> 20 [color=blue]
	16 [label="16	if ( ! HPATS ) {" shape=box]
	16 -> 17 [color=red]
	16 -> 18 [color=red]
	16 -> 20 [color=red]
	16 -> 21 [color=red]
	16 -> 22 [color=red]
	16 -> 23 [color=red]
	16 -> 24 [color=red]
	17 [label="17	jbig2_error ( ctx , JBIG2_SEVERITY_WARNING , segment -> number , \"no pattern dictionary found, skipping halftone image\" ) ;" shape=box]
	18 [label="18	return - 1 ;" shape=box]
	20 [label="20	HNUMPATS = HPATS -> n_patterns ;" shape=box]
	20 -> 37 [color=blue]
	20 -> 22 [color=blue]
	20 -> 39 [color=blue]
	21 [label="21	HBPP = 0 ;" shape=box]
	21 -> 22 [color=blue]
	21 -> 23 [color=blue]
	22 [label="22	while ( HNUMPATS > ( 1 << ++ HBPP ) ) ;" shape=box]
	22 -> 22 [color=red]
	23 [label="23	GI = jbig2_decode_gray_scale_image ( ctx , segment , data , size , params -> HMMR , params -> HGW , params -> HGH , HBPP , params -> HENABLESKIP , HSKIP , params -> HTEMPLATE , GB_stats ) ;" shape=box]
	23 -> 24 [color=blue]
	23 -> 49 [color=blue]
	23 -> 36 [color=blue]
	23 -> 47 [color=blue]
	24 [label="24	if ( ! GI ) {" shape=box]
	24 -> 44 [color=red]
	24 -> 45 [color=red]
	24 -> 49 [color=red]
	24 -> 50 [color=red]
	24 -> 25 [color=red]
	24 -> 26 [color=red]
	24 -> 28 [color=red]
	24 -> 29 [color=red]
	25 [label="25	jbig2_error ( ctx , JBIG2_SEVERITY_WARNING , segment -> number , \"unable to acquire gray-scale image, skipping halftone image\" ) ;" shape=box]
	26 [label="26	return - 1 ;" shape=box]
	28 [label="28	for ( mg = 0 ;" shape=box]
	28 -> 34 [color=blue]
	28 -> 35 [color=blue]
	28 -> 36 [color=blue]
	28 -> 29 [color=blue]
	29 [label="29	mg < params -> HGH ;" shape=box]
	29 -> 32 [color=red]
	29 -> 30 [color=red]
	29 -> 31 [color=red]
	30 [label="30	++ mg ) {" shape=box]
	31 [label="31	for ( ng = 0 ;" shape=box]
	31 -> 32 [color=blue]
	31 -> 34 [color=blue]
	31 -> 35 [color=blue]
	31 -> 36 [color=blue]
	32 [label="32	ng < params -> HGW ;" shape=box]
	32 -> 33 [color=red]
	32 -> 34 [color=red]
	32 -> 35 [color=red]
	32 -> 36 [color=red]
	32 -> 37 [color=red]
	32 -> 41 [color=red]
	33 [label="33	++ ng ) {" shape=box]
	34 [label="34	x = ( params -> HGX + mg * params -> HRY + ng * params -> HRX ) >> 8 ;" shape=box]
	34 -> 41 [color=blue]
	35 [label="35	y = ( params -> HGY + mg * params -> HRX - ng * params -> HRY ) >> 8 ;" shape=box]
	35 -> 41 [color=blue]
	36 [label="36	gray_val = GI [ ng ] [ mg ] ;" shape=box]
	36 -> 41 [color=blue]
	36 -> 37 [color=blue]
	36 -> 38 [color=blue]
	37 [label="37	if ( gray_val >= HNUMPATS ) {" shape=box]
	37 -> 38 [color=red]
	37 -> 39 [color=red]
	38 [label="38	jbig2_error ( ctx , JBIG2_SEVERITY_WARNING , segment -> number , \"gray-scale image uses value %d which larger than pattern dictionary\" , gray_val ) ;" shape=box]
	39 [label="39	gray_val = HNUMPATS - 1 ;" shape=box]
	39 -> 41 [color=blue]
	41 [label="41	jbig2_image_compose ( ctx , image , HPATS -> patterns [ gray_val ] , x , y , params -> op ) ;" shape=box]
	44 [label="44	for ( i = 0 ;" shape=box]
	44 -> 45 [color=blue]
	44 -> 47 [color=blue]
	45 [label="45	i < params -> HGW ;" shape=box]
	45 -> 46 [color=red]
	45 -> 47 [color=red]
	46 [label="46	++ i ) {" shape=box]
	47 [label="47	jbig2_free ( ctx -> allocator , GI [ i ] ) ;" shape=box]
	49 [label="49	jbig2_free ( ctx -> allocator , GI ) ;" shape=box]
	50 [label="50	return 0 ;" shape=box]
}
