digraph "Code Property Graph" {
	1 [label="1	static int jbig2_word_stream_buf_get_next_word ( Jbig2WordStream * self , int offset , uint32_t * word ) {" shape=box]
	1 -> 2 [color=blue]
	1 -> 5 [color=blue]
	1 -> 6 [color=blue]
	1 -> 11 [color=blue]
	1 -> 12 [color=blue]
	1 -> 14 [color=blue]
	2 [label="2	Jbig2WordStreamBuf * z = ( Jbig2WordStreamBuf * ) self ;" shape=box]
	2 -> 11 [color=blue]
	2 -> 3 [color=blue]
	2 -> 5 [color=blue]
	2 -> 6 [color=blue]
	3 [label="3	const byte * data = z -> data ;" shape=box]
	3 -> 12 [color=blue]
	3 -> 5 [color=blue]
	4 [label="4	uint32_t result ;" shape=box]
	5 [label="5	if ( offset + 4 < z -> size ) result = ( data [ offset ] << 24 ) | ( data [ offset + 1 ] << 16 ) | ( data [ offset + 2 ] << 8 ) | data [ offset + 3 ] ;" shape=box]
	5 -> 6 [color=red]
	5 -> 5 [color=red]
	5 -> 14 [color=red]
	5 -> 15 [color=red]
	5 -> 14 [color=blue]
	6 [label="6	else if ( offset > z -> size ) return - 1 ;" shape=box]
	6 -> 6 [color=red]
	6 -> 8 [color=red]
	6 -> 9 [color=red]
	6 -> 10 [color=red]
	6 -> 11 [color=red]
	6 -> 14 [color=red]
	6 -> 15 [color=red]
	8 [label="8	int i ;" shape=box]
	9 [label="9	result = 0 ;" shape=box]
	9 -> 12 [color=blue]
	9 -> 14 [color=blue]
	10 [label="10	for ( i = 0 ;" shape=box]
	10 -> 11 [color=blue]
	10 -> 12 [color=blue]
	11 [label="11	i < z -> size - offset ;" shape=box]
	11 -> 12 [color=red]
	12 [label="12	i ++ ) result |= data [ offset + i ] << ( ( 3 - i ) << 3 ) ;" shape=box]
	12 -> 11 [color=blue]
	12 -> 12 [color=blue]
	12 -> 14 [color=blue]
	14 [label="14	* word = result ;" shape=box]
	15 [label="15	return 0 ;" shape=box]
}
