digraph "Code Property Graph" {
	1 [label="1	int jbig2_end_of_stripe ( Jbig2Ctx * ctx , Jbig2Segment * segment , const uint8_t * segment_data ) {" shape=box]
	1 -> 9 [color=blue]
	1 -> 2 [color=blue]
	1 -> 4 [color=blue]
	2 [label="2	Jbig2Page page = ctx -> pages [ ctx -> current_page ] ;" shape=box]
	2 -> 11 [color=blue]
	2 -> 5 [color=blue]
	3 [label="3	int end_row ;" shape=box]
	4 [label="4	end_row = jbig2_get_int32 ( segment_data ) ;" shape=box]
	4 -> 9 [color=blue]
	4 -> 11 [color=blue]
	4 -> 5 [color=blue]
	5 [label="5	if ( end_row < page . end_row ) {" shape=box]
	5 -> 9 [color=red]
	5 -> 6 [color=red]
	6 [label="6	jbig2_error ( ctx , JBIG2_SEVERITY_WARNING , segment -> number , \"end of stripe segment with non-positive end row advance\" \" (new end row %d vs current end row %d)\" , end_row , page . end_row ) ;" shape=box]
	8 [label="8	else {" shape=box]
	9 [label="9	jbig2_error ( ctx , JBIG2_SEVERITY_INFO , segment -> number , \"end of stripe: advancing end row to %d\" , end_row ) ;" shape=box]
	11 [label="11	page . end_row = end_row ;" shape=box]
	12 [label="12	return 0 ;" shape=box]
}
